port = 8080
root = "liquidev.net/smugdancer"
gifski = "/usr/bin/gifski"

[cache]
dir = "cache"

# Development:
# limit = 16777216
# purge_limit = 8388608

# Production:
limit = 268435456
purge_limit = 234881024
