port = 8080
root = "liquidev.net/smugdancer"

[gif_service]
gifski = "/usr/bin/gifski"
cache_dir = "cache"

# Development:
cache_limit = 16777216
cache_purge_limit = 8388608

# Production:
# cache_limit = 268435456
# cache_purge_limit = 234881024

cache_purge_max_count = 8
