[server]
port = 8080
root = "localhost:8080"
reverse_proxy = false
rate_limiting = false  # REMOVE IN PROD

[render_service]
encoder = "target/release/giffel"
encoder_flags = [
    "stitch",
    "--archive", "data/frames.giffel",
    "--fps", "50",
    "--output", "-",
    "{frame_indices}"
]
max_jobs = 2

[cache_service]
cache_dir = "cache/gif"
database = "cache/cache.db"

# Development:
limit = 16777216
purge_limit = 8388608

# Production:
# limit = 268435456
# purge_limit = 234881024

purge_max_count = 8
