[server]
port = 8080
root = "localhost:8080"
reverse_proxy = false

[render_service]
encoder = "/usr/bin/gifski"
encoder_flags = [
    "--fps", "50",
    "--output", "-",
    "{input_filenames}"
]

[cache_service]
cache_dir = "cache/gif"
database = "cache/cache.db"

# Development:
limit = 16777216
purge_limit = 8388608

# Production:
# cache_limit = 268435456
# cache_purge_limit = 234881024

purge_max_count = 8
