[package]
name = "giffel"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.15", features = ["derive"] }
image = "0.24.3"
nanorand = "0.7.0"
parking_lot = "0.12.1"
pbr = "1.0.4"
rayon = "1.5.3"
thiserror = "1.0.31"
